baseURL = 'https://gohugo-theme-kmt.netlify.app/'
title = 'Kmt Hugo Theme'

languageCode = 'en-us'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.en]
    languageCode = 'en-us'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
  [languages.ar]
    languageCode = 'ar-eg'
    languageDirection = 'rtl'
    languageName = 'Arabic'
    weight = 2

title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
