baseURL = 'http://localhost:1313/'
languageCode = 'en-us'
title = 'KMT Theme'

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    languagedirection = 'ltr'
    title = 'KMT Theme'
    languageName = 'English'
    weight = 1
  [languages.ar]
    languagedirection = 'rtl'
    title = 'ثيم كِمْت'
    languageName = 'العربية'
    weight = 2

[params]
  founded = 2024

[module]
  [module.hugoVersion]
    extended = false
    min = "0.121.0"

enableGitInfo = true
showWordCounter = true
showReadTime = true

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4

[ad]
  href="https://www.waffarx.com/ar-us/r/DQUY5NYM"
  webp="/img/waffarx-banner.webp"
  png="/img/waffarx-banner.png"
  alt="waffarx cash back"