[build]
    publish = "public"
    command = "hugo -D --gc --minify"

[context.production.environment]
    HUGO_VERSION = "0.120.4"
    HUGO_ENV = "production"
    HUGO_ENABLEGITINFO = "true"

[context.split1]
    command = "hugo -D --gc --minify --enableGitInfo"

[context.split1.environment]
    HUGO_VERSION = "0.120.4"
    HUGO_ENV = "production"

[context.deploy-preview]
    command = "hugo -D --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
    HUGO_VERSION = "0.120.4"

[context.branch-deploy]
    command = "hugo -D --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
    HUGO_VERSION = "0.120.4"

[context.next.environment]
    HUGO_ENABLEGITINFO = "true"

[[redirects]]
    from= "/abanoubha"
    to="https://abanoubhanna.com/"
    status = 301
[[redirects]]
    from= "/developer"
    to="https://abanoubhanna.com/"
    status = 301
[[redirects]]
    from= "/github"
    to="https://github.com/abanoubha"
    status = 301
[[redirects]]
    from= "/code"
    to="https://github.com/abanoubha"
    status = 301
[[redirects]]
    from= "/source-code"
    to="https://github.com/abanoubha"
    status = 301
[[redirects]]
    from= "/twitter"
    to="https://twitter.com/abanoubha"
    status = 301
[[redirects]]
    from= "/x"
    to="https://x.com/abanoubha"
    status = 301
[[redirects]]
    from= "/linkedin"
    to="https://www.linkedin.com/in/abanoub-hanna"
    status = 301
[[redirects]]
    from= "/youtube"
    to="https://www.youtube.com/@abanoubha"
    status = 301
[[redirects]]
    from= "/yt"
    to="https://www.youtube.com/@abanoubha"
    status = 301
