name = 'kmt'
license = 'MIT'
licenselink = 'https://github.com/abanoubha/gohugo-theme-kmt/LICENSE'
description = 'experimental theme for Hugo SSG by @AbanoubHA'
homepage = 'https://github.com/abanoubha/gohugo-theme-kmt'
demosite = 'https://AbanoubHanna.com/'
tags = ['blog', 'company', 'fast', 'minimalist', 'responsive', 'simple', 'tags', 'keywords', 'related posts']
features = ['bilingual', 'minimal', 'fast', 'lazyloading images', 'related posts']

[author]
  name = 'Abanoub Hanna'
  homepage = 'https://abanoubhanna.com'
