title = "Notre-Dame de Paris"
baseURL = "https://kmt.netlify.app"
languageCode = "en-us"
theme = ["github.com/abanoubha/gohugo-theme-kmt"]
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.en]
    title = "kmt"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "kmt ar"
    weight = 2
    contentDir = "content/ar"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = "/images/favicon.png"
  site_logo = ""
  description = "The last theme you'll ever need.
  background_color_class = "bg-black"
  recent_posts_number = 10

[[params.kmt_socials]]
name = "x (pka twitter)"
url = "https://twitter.com/abanoubha"
